#!/usr/bin/env bash

set -e

# shellcheck source=/dev/null
. ~/bin/include/utils.sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# org-refcard on github
ORGREF="https://raw.githubusercontent.com/fniessen/refcard-org-mode/master/README.org"
OUTFILE="$DIR/org-refcard.org"

##
# @info         Donwload org-refcard
# @param        update even if present (optional)
##
org_refcard() {
    if [[ ! -f "$OUTFILE" || -n "$1" ]]; then
        _log "Downloading org-refcard"
        wget "$ORGREF" -O "$OUTFILE" >/dev/null 2>&1
    else
        _log "org-recard already downloaded"
    fi
}

if [[ "$#" -eq 0 ]]; then
    _usage_from_args
fi

while (( "$#" )); do
    case "$1" in
        -i|--install) org_refcard;;
        -u|--update-docs) org_refcard -u;;
        *) echo -e "\e[40m\e[1;32mUsage: $0 [-u|-i]\e[0m";
           exit 1;;
    esac
    shift
done
