#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit
. ~/bin/utils.sh 

function install() {
    # https://neo4j.com/docs/operations-manual/current/installation/linux/debian/
    if ! hash neo4j 2>/dev/null ; then
        _log "Installing neo4j"
        wget -O - https://debian.neo4j.org/neotechnology.gpg.key | sudo apt-key add -
        echo 'deb http://debian.neo4j.org/repo stable/' | 
            sudo tee -a /etc/apt/sources.list.d/neo4j.list
        sudo apt-get update
        sudo apt-get install -y neo4j=3.2.3 # community edition
        
        # enable shell
        sudo sed -i "s/^#\s*dbms.shell/dbms.shell/g" /etc/neo4j/neo4j.conf 
    else 
        _log "Already have neo4j"
    fi
}

"$@"
