language: generic
sudo: required
dist: trusty

env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"

  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot

branches:
  only:
    - master

install:
  - if [ "$EMACS" = 'emacs24' ]; then
      sudo apt-get -qq update &&
      sudo apt-get -qq -f install &&
      sudo apt-get -qq install emacs24 emacs24-el;
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
      sudo apt-get -qq update &&
      sudo apt-get -qq -f install &&
      sudo apt-get -qq install emacs-snapshot &&
      sudo apt-get -qq install emacs-snapshot-el;
    fi
  # - $CURL https://raw.githubusercontent.com/nverno/nvp/master/nvp-path.el -o nvp-path.el
  - git clone https://github.com/nverno/nvp
  - $EMACS --version
  
script:
  - make test

notifications:
  email:
    on_success: never
    on_failure: always
