#+TITLE: Assorted macros - some useful, many not

Note: these are currently all required by nvp-macro.el, so that file should be
recompiled anytime any of these change. It would be nice to remove the setup
macros to just be required during init/config compiling.

* nvp-macs-setup.el
these are not necessarily hygenic, stuff in here should just be used for
compilation of init/configs.

* nvp-macs-bindings.el
binding related macros - probably try to consolodate these to a couple of
generally useful ones. would be nice to get down to just `nvp-bindings`

* nvp-macs-common.el
included by other macros, but shouldn't include any others to avoid cyclics.
- OS
- classic anamorphs:
  - if, when, 
- cl-defstruct / CLOS helpers
- conversions
- helper funcs to normalize variables / macro arguments
- declare / autoload wrappers
- simple string/regex wrappers
- get load-file
- input wrapper to get last input char/command/event

* nvp-macs-process.el
process macros - probably slim this down to one or two useful ones as well.
