;;; c/c++ system includes - generated by includes.sh

(defconst nvp-c-include-dirs
  (list
   "/usr/lib/gcc/x86_64-linux-gnu/7/include"
   "/usr/local/include"
   "/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed"
   "/usr/include/x86_64-linux-gnu"
   "/usr/include"
))

(defconst nvp-c++-include-dirs
  (list
   "/usr/include/c++/7"
   "/usr/include/x86_64-linux-gnu/c++/7"
   "/usr/include/c++/7/backward"
   "/usr/lib/gcc/x86_64-linux-gnu/7/include"
   "/usr/local/include"
   "/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed"
   "/usr/include/x86_64-linux-gnu"
   "/usr/include"
))

(defconst nvp-clang-c-include-dirs
 (list
   "/usr/local/include"
   "/usr/lib/llvm-6.0/lib/clang/6.0.0/include"
   "/usr/include/x86_64-linux-gnu"
   "/usr/include"
))

(defconst nvp-clang-c++-include-dirs
 (list
   "/usr/include/c++/7.3.0"
   "/usr/include/x86_64-linux-gnu/c++/7.3.0"
   "/usr/include/c++/7.3.0/backward"
   "/usr/include/clang/6.0.0/include"
   "/usr/local/include"
   "/usr/include/x86_64-linux-gnu"
   "/usr/include"
))
(provide 'nvp-c-include)